@OrderAggregator_HostAddress = https://localhost:7251

POST {{OrderAggregator_HostAddress}}/api/order
Content-Type: application/json

[
  {
    "productId": 0,
    "quantity": 2
  },
  {
    "productId": 1,
    "quantity": 1
  }

]

###

GET {{OrderAggregator_HostAddress}}/api/order

###
